AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3ChallengeBucketName:
    Type: String
    Description: "S3 Challenge bucket name"
    Default: juans-challenge-bucket-name
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3ChallengeBucketName
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: "Name of created bucket"